version: "3"
services:
  mongodb:
    image: 'mongo'
    container_name: 'todo'
    ports:
      - "27017:27017"
  server:
    build: .
    command: npm start
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    links:
      - mongodb
